services:
  nuxt-app:
    image: nuxt-app
    build: .
    container_name: nuxt-app
    ports:
      - "3030:3000"
    environment:
      - SITE_URL=${SITE_URL:-http://localhost:3030}
      - NODE_ENV=production
